# Generated by Django 4.1.1 on 2022-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tokenstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenstable',
            name='userid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
