# Generated by Django 4.1.1 on 2022-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tokenstable_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshToken',
            field=models.TextField(),
        ),
    ]
